print("#########")
print("# O   O #")
print("#   +   #")
print("#   -   #")
print("#########")
print("    #")
print("    #")

print(" Please enter a character for the eye")
eye = input()
print(" Beep's expression is now as follows: ")

print("#########")
print("# " + eye + "   " + eye +" # ")
print("#   +   #")
print("#   -   #")
print("#########")
print("    #")
print("    #")